/*
 * This source file was generated by the Gradle 'init' task
 */
package dbl;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Test {
    @Test void appWorks() {
        Legends leTest = new Legends();
        assertNotNull(leTest.shouldRun(), "perhaps it has started");
    }
}
